In [1]:
import numpy as np

In [2]:
x=np.ones((2,3,4))

In [3]:
x

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [4]:
res=[]
for i in range(2):
    x00=x[i,:,:]
    res.append(np.sum(x00,axis=1))

In [5]:
x00

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.sum(x00,axis=1).T

array([4., 4., 4.])

In [7]:
np.array(res)

array([[4., 4., 4.],
       [4., 4., 4.]])

In [2]:
import numpy as np

In [3]:
x2=np.random.randint(0,2,(2,4,4))

In [4]:
x2

array([[[1, 1, 0, 1],
        [0, 1, 0, 1],
        [0, 1, 0, 0],
        [1, 1, 1, 0]],

       [[0, 0, 1, 0],
        [0, 1, 0, 0],
        [1, 1, 0, 1],
        [1, 1, 1, 1]]])

In [5]:
#除去起点和终点：剩下的每一个点都是出边和等于入边和
#反应在距离矩阵中就是：第i行（以i为起点，i!=o,i!=d）的和等于等i列（以i为终点）的和

In [6]:
s_row=np.sum(x2,axis=2)
s_row

array([[3, 2, 1, 3],
       [1, 1, 3, 4]])

In [7]:
s_col=np.sum(x2,axis=1)
s_col

array([[2, 4, 1, 2],
       [2, 3, 2, 2]])

In [9]:
s_row[:,1:-1]

array([[2, 1],
       [1, 3]])

In [10]:
s_col[:,1:-1]

array([[4, 1],
       [3, 2]])

In [11]:
s_row[:,1:-1]-s_col[:,1:-1]

array([[-2,  0],
       [-2,  1]])

In [ ]:
###出边和或者入边和小于等于1

In [ ]:
s_row<=1
s_col<=1

In [ ]:
##起点出边和为1，入边和为0

In [ ]:
# 第0行和为1，第0列和为0

In [14]:
r0=x2[:,0,:,None]
r0

array([[[1],
        [1],
        [0],
        [1]],

       [[0],
        [0],
        [1],
        [0]]])

In [17]:
np.sum(r0,axis=1)#==1

array([[3],
       [1]])

In [18]:
c0=x2[:,:,0,None]
c0

array([[[1],
        [0],
        [0],
        [1]],

       [[0],
        [0],
        [1],
        [1]]])

In [19]:
np.sum(c0,axis=1)#==0

array([[2],
       [2]])

In [ ]:
#终点出边和为0，入边和为1

In [ ]:
##第n行和为0；第n列和为1

In [21]:
rn=x2[:,-1,:,None]
rn

array([[[1],
        [1],
        [1],
        [0]],

       [[1],
        [1],
        [1],
        [1]]])

In [22]:
np.sum(rn,axis=1)#==0

array([[3],
       [4]])

In [23]:
cn=x2[:,:,-1,None]
cn

array([[[1],
        [1],
        [0],
        [0]],

       [[0],
        [0],
        [1],
        [1]]])

In [24]:
np.sum(cn,axis=1)#==1

array([[2],
       [2]])

In [30]:
res=np.array(
[[0, 1, 0, 0, 0, 0, 0, 0, 0, 0,],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0,],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1,],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0,],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,],])

In [31]:
res

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [37]:
for i in range(10):
    for j in range(10):
        if res[i,j]>0:
            print(i,j)

0 1
1 5
4 9
5 4


In [34]:
# res2=[]
# for i in range(2):
#     x00=x2[i,:,:]
#     res2.append(np.sum(x00,axis=1))

In [36]:
# res

In [37]:
# res2

In [38]:
# np.array(res)-np.array(res2)

In [39]:
#行和
np.sum(x2,axis=2)

array([[3, 3, 1, 2],
       [3, 1, 3, 1]])

In [40]:
#列和
np.sum(x2,axis=1)

array([[3, 2, 1, 3],
       [1, 3, 2, 2]])

In [ ]:
# 两个都去除第一列

In [41]:
r2=x2[:,:,0,None]

In [42]:
r2

array([[[1],
        [1],
        [0],
        [1]],

       [[0],
        [0],
        [1],
        [0]]])

In [43]:
np.sum(r2,axis=1)

array([[3],
       [1]])

In [44]:
r3=x2[:,0,:,None]

In [45]:
r3

array([[[1],
        [1],
        [0],
        [1]],

       [[0],
        [1],
        [1],
        [1]]])

In [47]:
np.sum(r3,axis=1)

array([[3],
       [3]])

In [49]:
np.abs(r3)-1

array([[[ 0],
        [ 0],
        [-1],
        [ 0]],

       [[-1],
        [ 0],
        [ 0],
        [ 0]]])

In [54]:
np.abs(np.sum(x2[:, -1, :, None], axis=1))

array([[2],
       [1]])

In [55]:
np.abs(np.sum(x2[:,: , -1, None], axis=1) )

array([[3],
       [2]])

In [2]:
nodes = [ [2, 3], [3, 4, 5], [5, 6], [7, 8], [4, 6], [7, 9], [8, 9], [9, 10], [10]]
    

In [1]:
import numpy as np
import pandas as pd

In [2]:
graph={
    1:[[2,3],[394,150]],
    2:[[5],[251]],
    3:[[4],[113]],
    4:[[5],[358]],
    5:[[6],[357]],
    6:[[7,8],[248,145]],
    7:[[10],[252]],
    8:[[9],[110]],
    9:[[12],[299]],
    10:[[11],[200]],
    11:[[16],[396]],
   12 :[[13],[113]],
    13:[[14],[142]],
    14:[[15,24,27],[80,760,170]],
    15:[[16],[192]],
    17:[[18,28],[179,159]],
    18:[[19],[118]],
    19:[[20],[143]],
    20:[[21],[428]],
    21:[[22],[97]],
    22:[[23],[96]],
    23:[[24],[172]],
    24:[[25],[150]],
    25:[[26,33],[106,244]],
    26:[[27],[627]],
    27:[[35],[286]],
    28:[[29,37],[36,259]],
    29:[[30],[68]],
     30:[[31,38],[322,260]],
    31:[[59],[87]],
    32:[[33,59],[105,251]],
    33:[[34],[78]],
    34:[[35,43],[806,114]],
    35:[[36],[59]],
    36:[[53],[135]],
    37:[[38],[109]],
    38:[[39,40],[383,20]],
    39:[[41],[49]],
    40:[[45],[93]],
    41:[[42,46],[231,112]],
    42:[[44],[143]],
    43:[[44],[117]],
    44:[[47],[148]],
    45:[[46],[387]],
     46:[[47],[378]],
    47:[[48,58],[239,278]],
    48:[[49],[297]],
    49:[[50],[201]],
    50:[[51],[102]],
    51:[[52,54],[72,209]],
    52:[[53],[69]],
    54:[[55],[156]],
    55 :[[56],[234]],
    56:[[57],[738]],
    57:[[58],[194]],
    
}

In [3]:
graph

{1: [[2, 3], [394, 150]],
 2: [[5], [251]],
 3: [[4], [113]],
 4: [[5], [358]],
 5: [[6], [357]],
 6: [[7, 8], [248, 145]],
 7: [[10], [252]],
 8: [[9], [110]],
 9: [[12], [299]],
 10: [[11], [200]],
 11: [[16], [396]],
 12: [[13], [113]],
 13: [[14], [142]],
 14: [[15, 24, 27], [80, 760, 170]],
 15: [[16], [192]],
 17: [[18, 28], [179, 159]],
 18: [[19], [118]],
 19: [[20], [143]],
 20: [[21], [428]],
 21: [[22], [97]],
 22: [[23], [96]],
 23: [[24], [172]],
 24: [[25], [150]],
 25: [[26, 33], [106, 244]],
 26: [[27], [627]],
 27: [[35], [286]],
 28: [[29, 37], [36, 259]],
 29: [[30], [68]],
 30: [[31, 38], [322, 260]],
 31: [[59], [87]],
 32: [[33, 59], [105, 251]],
 33: [[34], [78]],
 34: [[35, 43], [806, 114]],
 35: [[36], [59]],
 36: [[53], [135]],
 37: [[38], [109]],
 38: [[39, 40], [383, 20]],
 39: [[41], [49]],
 40: [[45], [93]],
 41: [[42, 46], [231, 112]],
 42: [[44], [143]],
 43: [[44], [117]],
 44: [[47], [148]],
 45: [[46], [387]],
 46: [[47], [378]],
 47: [[48, 58], [239,

In [4]:
graph[1][0]

[2, 3]

In [5]:

graph[1][1]

[394, 150]

In [3]:
# ls

In [1]:
import json
#节点序号从零开始，索引和序号就相同
with open('可达矩阵结果1.json') as f:
        data_json=json.load(f)
#         print(data)
        nodes_amount=len(data_json)
        

In [2]:
data_json

{'0': [[1, 2, 5], [1003.669, 560.926, 393.475]],
 '1': [[0, 3], [1003.669, 385.485]],
 '2': [[4, 0, 19], [378.977, 560.926, 1505.925]],
 '3': [[5, 1, 10], [992.626, 385.485, 326.239]],
 '4': [[5, 2], [341.379, 378.977]],
 '5': [[4, 3, 0, 8], [341.379, 992.626, 393.475, 285.505]],
 '6': [[22], [1728.659]],
 '7': [[14, 8], [323.511, 387.877]],
 '8': [[9, 5, 7], [468.571, 285.505, 387.877]],
 '9': [[8, 13, 10], [468.571, 231.991, 494.969]],
 '10': [[3, 9, 11], [326.239, 494.969, 203.838]],
 '11': [[12, 10], [323.326, 203.838]],
 '12': [[11, 17, 13], [323.326, 617.804, 95.572]],
 '13': [[14, 9, 12], [864.251, 231.991, 95.572]],
 '14': [[13, 7, 16], [864.251, 323.511, 492.093]],
 '15': [[18], [643.609]],
 '16': [[17, 20, 14], [844.263, 337.114, 492.093]],
 '17': [[16, 12, 21], [844.263, 617.804, 331.594]],
 '18': [[22, 15, 19], [746.898, 643.609, 220.758]],
 '19': [[2, 20, 18, 23], [1505.925, 448.873, 220.758, 750.75]],
 '20': [[19, 21, 16, 25], [448.873, 787.453, 337.114, 758.19]],
 '21': 

In [3]:
nodes_amount

34

In [37]:
row=[]
col=[]
data=[]
MSF_data=[]
FHV_data=[]
FD_data=[]
FW_data=[]
FF_data=[]
# MSF[distance>0]=420
# FHV[distance>0]=0.333
# FD[distance>0]=0.97
# FW==1
# FF[distance>0]=0.95
for node_1,v in data_json.items():
    
    next_node_list=v[0]
    weight_list=v[1]
#     print(node_1,next_node_list,weight_list)
    for next_node,weight in zip(next_node_list,weight_list):
        row.append(node_1)
        col.append(next_node)
#         print(next_node,weight)
        data.append(weight)
        MSF_data.append(420)
        FHV_data.append(0.333)
        FD_data.append(0.97)
        FW_data.append(0.84)
        FF_data.append(0.95)

In [38]:
# row

In [39]:
# col

In [40]:
len(row)

88

In [41]:
len(col)

88

In [42]:
m = sparse.csc_matrix((data, (row, col)), shape=(nodes_amount, nodes_amount))
MSF=sparse.csc_matrix((MSF_data, (row, col)), shape=(nodes_amount, nodes_amount))
FHV=sparse.csc_matrix((FHV_data, (row, col)), shape=(nodes_amount, nodes_amount))
FD=sparse.csc_matrix((FD_data, (row, col)), shape=(nodes_amount, nodes_amount))
FW=sparse.csc_matrix((FW_data, (row, col)), shape=(nodes_amount, nodes_amount))
FF=sparse.csc_matrix((FF_data, (row, col)), shape=(nodes_amount, nodes_amount))





In [43]:
import pandas as pd

In [44]:
distance=pd.SparseDataFrame(data=m).to_dense()
MSF=pd.SparseDataFrame(data=MSF).to_dense()
FHV=pd.SparseDataFrame(data=FHV).to_dense()
FD=pd.SparseDataFrame(data=FD).to_dense()
FW=pd.SparseDataFrame(data=FW).to_dense()
FF=pd.SparseDataFrame(data=FF).to_dense()

In [45]:
distance.head()

0         1        2        3        4        5   6   7   8   9   \
0       NaN  1003.669  560.926      NaN      NaN  393.475 NaN NaN NaN NaN   
1  1003.669       NaN      NaN  385.485      NaN      NaN NaN NaN NaN NaN   
2   560.926       NaN      NaN      NaN  378.977      NaN NaN NaN NaN NaN   
3       NaN   385.485      NaN      NaN      NaN  992.626 NaN NaN NaN NaN   
4       NaN       NaN  378.977      NaN      NaN  341.379 NaN NaN NaN NaN   

   ...  24  25  26  27  28  29  30  31  32  33  
0  ... NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  
1  ... NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  
2  ... NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  
3  ... NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  
4  ... NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  

[5 rows x 34 columns]

In [46]:
distance.to_csv('distance1.csv',index=False,header=None)
MSF.to_csv('MSF1.csv',index=False,header=None)
FHV.to_csv('FHV1.csv',index=False,header=None)
FD.to_csv('FD1.csv',index=False,header=None)
FW.to_csv('FW1.csv',index=False,header=None)
FF.to_csv('FF1.csv',index=False,header=None)

In [107]:
for i in range(nodes_amount):
    for j in range(nodes_amount):
        if m[i,j]!=m[j,i]:
            print(m[i,j],m[j,i])
            break

In [20]:
m[20,17]

0.0

In [112]:
m[17,20]

912.8402411397454

In [105]:
m.shape

(33, 33)

In [90]:
m[m>0]

matrix([[ 143.55366415,  577.42923191,  816.08999375,  868.70225948,
          480.72628251, 1229.06774948,  128.727783  ,  463.03259198,
          998.69439002, 1838.3051602 , 1218.13132864,  365.75524475,
          466.75711245,  128.727783  ,  418.96391472,  928.53586038,
         1747.76248325,  480.72628251, 1218.13132864,  418.96391472,
          348.81458496, 2103.56072041,  463.03259198,  476.0306985 ,
          395.26601694,  348.81458496,  476.0306985 ,  575.03794492,
          575.03794492,  607.40272503,  283.41877214,  365.75524475,
          607.40272503,  562.58115125,  562.58115125,  117.18990239,
          754.88388485,  283.41877214,  117.18990239, 1060.59946619,
          395.26601694, 1060.59946619,  601.24070556,  998.69439002,
          928.53586038,  784.12825173,  871.9568033 ,  601.24070556,
         1035.24898715,  411.88763547,  754.88388485, 1035.24898715,
          405.18129121,  784.12825173,  270.57465746,  912.84024114,
         1838.3051602 , 1747.76248

In [106]:
FF[0:10,0:10].toarray()

array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.95, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.95, 0.  , 0.  , 0.95, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.95, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.95, 0.  , 0.  , 0.95, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.95, 0.  , 0.95, 0.95, 0.  , 0.  , 0.  , 0.95, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.95, 0.  , 0.  , 0.  , 0.  , 0.  , 0.95, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.95, 0.  , 0.95, 0.  , 0.95],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.95, 0.  ]])

In [88]:
m[0:10,0:10].toarray()

array([[   0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ],
       [   0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,  480.72628251,    0.        ,    0.        ,
           0.        ,    0.        ],
       [   0.        ,    0.        ,    0.        ,    0.        ,
         128.727783  ,    0.        ,    0.        ,  463.03259198,
           0.        ,    0.        ],
       [   0.        ,    0.        ,    0.        ,    0.        ,
           0.        , 1218.13132864,    0.        ,    0.        ,
           0.        ,    0.        ],
       [   0.        ,    0.        ,  128.727783  ,    0.        ,
           0.        ,  418.96391472,    0.        ,    0.        ,
           0.        ,    0.        ],
       [   0.        ,  480.72628251,    0.        , 1218.13132864,
         418.96391472,    0.        ,    0.        ,    0

In [12]:
from scipy import sparse
row = [0, 1, 2, 2]
col = [0, 1, 2, 3]
data = [1, 2, 3, 4]
m = sparse.csc_matrix((data, (row, col)), shape=(4, 4))
m


<4x4 sparse matrix of type '<class 'numpy.intc'>'
	with 4 stored elements in Compressed Sparse Column format>

In [41]:
m[0,0]

1

In [10]:
import numpy as np

import scipy.sparse as sp

A=np.array([[1,0,2,0],[0,0,0,0],[3,0,0,0],[1,0,0,4]])

AS=sp.csc_matrix(A)

print(AS)

# print(AS.data)

# print(AS.indptr)

# print(AS.indices)

# print(AS.nnz)    #运行结果：

# [1 3 1 2 4]

# [0 3 3 4 5]     #注意此处，同一矩阵CSR格式的indptr为[0 2 2 3 5]

# [0 2 3 0 3]

# 5

  (0, 0)	1
  (2, 0)	3
  (3, 0)	1
  (0, 2)	2
  (3, 3)	4


In [18]:
AS[0,0]=10

In [28]:
print(AS[0:3,0:3].toarray())

[[10  0  2]
 [ 0  0  0]
 [ 3  0  0]]


In [34]:
from numpy import array
row = array([0,2,2,0,1,2])
col = array([0,0,1,2,2,2])
data = array([1,2,3,4,5,6])
dd=sp.csc_matrix( (data,(row,col)), shape=(3,3) ).todense()
dd

matrix([[1, 0, 4],
        [0, 0, 5],
        [2, 3, 6]], dtype=int32)

In [35]:
dd[0,0]=10

In [36]:
dd[0,0]

10

In [6]:
distance=np.zeros((59,59))

In [7]:
distance

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [8]:
for node_1,v in graph.items():
    next_node_list=v[0]
    weight_list=v[1]
#     print(node_1,next_node_list,weight_list)
    for next_node,weight in zip(next_node_list,weight_list):
#         print(next_node,weight)
        distance[node_1-1,next_node-1]=weight
        
    

In [9]:
dim=59
for i in range(dim):
    for j in range(dim):
        if i>j:
            distance[i,j]=distance[j,i]

In [10]:
import pandas as pd
df=pd.DataFrame(data=distance)

In [11]:
df.to_csv('distance.csv',index=False,header=None)

In [12]:
distance>0

array([[False,  True,  True, ..., False, False, False],
       [ True, False, False, ..., False, False, False],
       [ True, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False,  True, False],
       [False, False, False, ...,  True, False, False],
       [False, False, False, ..., False, False, False]])

In [13]:
'''
MSF=pd.read_excel(path,'MSF（最大服务交通量）').iloc[:,1:]#,'B2:K11');#读取路段的最大服务交通量
FHV=pd.read_excel(path,'FHV（交通组成修正系数）').iloc[:,1:]#,'B2:K11');#读取交通组成修正系数
FD=pd.read_excel(path,'FD（方向分布系数）').iloc[:,1:]#,'B2:K11');  #读取方向分布修正系数
FW=pd.read_excel(path,'FW（宽度修正系数）').iloc[:,1:]#,'B2:K11');  #读取车道宽度、路肩宽度修正系数
FF=pd
'''

"\nMSF=pd.read_excel(path,'MSF（最大服务交通量）').iloc[:,1:]#,'B2:K11');#读取路段的最大服务交通量\nFHV=pd.read_excel(path,'FHV（交通组成修正系数）').iloc[:,1:]#,'B2:K11');#读取交通组成修正系数\nFD=pd.read_excel(path,'FD（方向分布系数）').iloc[:,1:]#,'B2:K11');  #读取方向分布修正系数\nFW=pd.read_excel(path,'FW（宽度修正系数）').iloc[:,1:]#,'B2:K11');  #读取车道宽度、路肩宽度修正系数\nFF=pd\n"

In [14]:
MSF=np.ones((dim,dim))
MSF[distance>0]=420
MSF

array([[  1., 420., 420., ...,   1.,   1.,   1.],
       [420.,   1.,   1., ...,   1.,   1.,   1.],
       [420.,   1.,   1., ...,   1.,   1.,   1.],
       ...,
       [  1.,   1.,   1., ...,   1., 420.,   1.],
       [  1.,   1.,   1., ..., 420.,   1.,   1.],
       [  1.,   1.,   1., ...,   1.,   1.,   1.]])

In [11]:
FHV=np.ones((dim,dim))
# MSF[distance>0]=420
FHV[distance>0]=0.333
FHV

array([[1.   , 0.333, 0.333, ..., 1.   , 1.   , 1.   ],
       [0.333, 1.   , 1.   , ..., 1.   , 1.   , 1.   ],
       [0.333, 1.   , 1.   , ..., 1.   , 1.   , 1.   ],
       ...,
       [1.   , 1.   , 1.   , ..., 1.   , 0.333, 1.   ],
       [1.   , 1.   , 1.   , ..., 0.333, 1.   , 1.   ],
       [1.   , 1.   , 1.   , ..., 1.   , 1.   , 1.   ]])

In [15]:
FD=np.ones((dim,dim))
# MSF[distance>0]=420
# FHV[distance>0]=0.333
FD[distance>0]=0.97
FD

array([[1.  , 0.97, 0.97, ..., 1.  , 1.  , 1.  ],
       [0.97, 1.  , 1.  , ..., 1.  , 1.  , 1.  ],
       [0.97, 1.  , 1.  , ..., 1.  , 1.  , 1.  ],
       ...,
       [1.  , 1.  , 1.  , ..., 1.  , 0.97, 1.  ],
       [1.  , 1.  , 1.  , ..., 0.97, 1.  , 1.  ],
       [1.  , 1.  , 1.  , ..., 1.  , 1.  , 1.  ]])

In [ ]:
# MSF[distance>0]=420
# FHV[distance>0]=0.333
# FD[distance>0]=0.97
# FW==1
FF[distance>0]=0.95

In [16]:
FW=np.ones((dim,dim))
FW[distance==0]=0.00009
FW

array([[9.e-05, 1.e+00, 1.e+00, ..., 9.e-05, 9.e-05, 9.e-05],
       [1.e+00, 9.e-05, 9.e-05, ..., 9.e-05, 9.e-05, 9.e-05],
       [1.e+00, 9.e-05, 9.e-05, ..., 9.e-05, 9.e-05, 9.e-05],
       ...,
       [9.e-05, 9.e-05, 9.e-05, ..., 9.e-05, 1.e+00, 9.e-05],
       [9.e-05, 9.e-05, 9.e-05, ..., 1.e+00, 9.e-05, 9.e-05],
       [9.e-05, 9.e-05, 9.e-05, ..., 9.e-05, 9.e-05, 9.e-05]])

In [17]:
FF=np.ones((dim,dim))
FF[distance>0]=0.95
FF

array([[1.  , 0.95, 0.95, ..., 1.  , 1.  , 1.  ],
       [0.95, 1.  , 1.  , ..., 1.  , 1.  , 1.  ],
       [0.95, 1.  , 1.  , ..., 1.  , 1.  , 1.  ],
       ...,
       [1.  , 1.  , 1.  , ..., 1.  , 0.95, 1.  ],
       [1.  , 1.  , 1.  , ..., 0.95, 1.  , 1.  ],
       [1.  , 1.  , 1.  , ..., 1.  , 1.  , 1.  ]])

In [12]:
# MSF=pd.DataFrame(data=MSF)
FHV=pd.DataFrame(data=FHV)
# FD=pd.DataFrame(data=FD)
# FW=pd.DataFrame(data=FW)
# FF=pd.DataFrame(data=FF)

In [13]:
# MSF.to_csv('MSF.csv',index=False,header=None)
FHV.to_csv('FHV.csv',index=False,header=None)
# FD.to_csv('FD.csv',index=False,header=None)
# FW.to_csv('FW.csv',index=False,header=None)
# FF.to_csv('FF.csv',index=False,header=None)


In [21]:
cell_node={
    
'一棒':31,
'高线':42,
'二棒':40,
'三棒':45,
'炼焦厂_1':31,
'老炼钢':43,
'新炼钢':32,
'原料场':3,
'球团厂':23,
'265+400烧结厂':26,
'炼铁5':48,
'窄带':58,
'450烧结':8,
'炼铁1-4':9,
'石灰厂':15,
'废钢堆场':46,

}

In [22]:
cell_node

{'一棒': 31,
 '高线': 42,
 '二棒': 40,
 '三棒': 45,
 '炼焦厂_1': 31,
 '老炼钢': 43,
 '新炼钢': 32,
 '原料场': 3,
 '球团厂': 23,
 '265+400烧结厂': 26,
 '炼铁5': 48,
 '窄带': 58,
 '450烧结': 8,
 '炼铁1-4': 9,
 '石灰厂': 15,
 '废钢堆场': 46}

In [23]:
# ls

In [24]:
import pandas as pd

In [47]:
path='日照钢铁物料运输量表.xls'
ysl_new=pd.read_excel(path)

In [53]:
ysl_new=ysl_new[~ysl_new['重车起点'].isnull()]

In [54]:
ysl_new.shape

(64, 15)

In [55]:
ysl_new.tail()

流转类型 运输方式 来源单元     到达单元      物质名称    物质量      日运输量  重车起点  重车终点  空车起点  \
59  回收物流   道路  炼钢3  铁钢渣处理_1       精炼渣  32.75  0.093571   0.0  23.0  23.0   
60  回收物流   道路  炼钢3  铁钢渣处理_1       脱硫渣  12.28  0.035086   0.0  23.0  23.0   
61  回收物流   道路  炼钢3  铁钢渣处理_1      炼钢残钢  10.65  0.030429   0.0  23.0  23.0   
62  回收物流   道路  炼钢3  铁钢渣处理_1   中间包冷钢废钢   5.73  0.016371   0.0  23.0  23.0   
63  回收物流   道路  炼钢3  铁钢渣处理_1  氧化铁皮、切割渣   3.68  0.010514   0.0  23.0  23.0   

    空车终点  运输车辆的最大装载量  车次  日运输量新  车辆折算系数  
59   0.0         NaN NaN    NaN     NaN  
60   0.0         NaN NaN    NaN     NaN  
61   0.0         NaN NaN    NaN     NaN  
62   0.0         NaN NaN    NaN     NaN  
63   0.0         NaN NaN    NaN     NaN

In [56]:
ysl_new.head()

流转类型 运输方式 来源单元    到达单元        物质名称    物质量      日运输量  重车起点  重车终点  空车起点  \
0  回收物流   道路  炼钢1  废钢堆场_1  钢水罐铸余及事故钢水   9.37  0.026771  28.0  15.0  15.0   
1  回收物流   道路  炼钢1  废钢堆场_1      连铸切头切尾   4.68  0.013371  28.0  15.0  15.0   
2  回收物流   道路  炼钢1  废钢堆场_1     废连铸坯及试样   2.60  0.007429  28.0  15.0  15.0   
3  回收物流   道路  炼钢1  废钢堆场_1      连铸废旧备件   1.33  0.003800  28.0  15.0  15.0   
4  回收物流   道路  炼钢1    原料厂1       炼钢集尘粉  20.82  0.059486  28.0  17.0  17.0   

   空车终点  运输车辆的最大装载量  车次  日运输量新  车辆折算系数  
0  28.0         NaN NaN    NaN     NaN  
1  28.0         NaN NaN    NaN     NaN  
2  28.0         NaN NaN    NaN     NaN  
3  28.0         NaN NaN    NaN     NaN  
4  28.0         NaN NaN    NaN     NaN

In [27]:
set(ysl['来源单元'].unique())-set(cell_node.keys())

{'东门', '仓库', '北门', '厂外', '水渣堆场', '铁钢渣处理'}

In [28]:
set(ysl['到达单元'].unique())-set(cell_node.keys())

{'东门', '中央水处理', '仓库', '北门', '厂外', '循环经济园', '水渣堆场', '煤净', '铁钢渣处理'}

In [29]:
ysl_new=ysl[(ysl['来源单元'].isin(cell_node.keys())) & (ysl['到达单元'].isin(cell_node.keys()))]

In [30]:
ysl_new['来源单元'].unique()

array(['石灰厂', '原料场', '老炼钢', '新炼钢', '废钢堆场', '炼铁1-4', '炼铁5', '一棒', '450烧结',
       '265+400烧结厂', '炼焦厂_1', '球团厂'], dtype=object)

In [31]:
ysl_new['到达单元'].unique()

array(['新炼钢', '老炼钢', '二棒', '高线', '窄带', '三棒', '一棒', '原料场', '废钢堆场', '450烧结',
       '265+400烧结厂', '炼铁1-4', '炼焦厂_1', '炼铁5', '球团厂', '石灰厂'], dtype=object)

In [32]:
ysl_new.shape

(95, 7)

In [33]:
ysl_new['日运输量']=ysl_new['物质量']/365

f:\陶士来文件\software\python3_6_5\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [34]:
ysl_new.sort_values(by='日运输量',ascending=False).head()

流转类型 运输方式   来源单元   到达单元 物质名称 物质品类     物质量      日运输量
210   铁前   胶带    原料场  450烧结  铁矿粉   原料  554.15  1.518219
211   铁前   公路  450烧结  炼铁1-4  烧结矿   主料  482.95  1.323151
213   铁前   胶带    原料场  炼焦厂_1  洗精煤   燃料  347.40  0.951781
207   铁钢   公路  炼铁1-4    新炼钢   铁水   主料  320.00  0.876712
208   铁钢   公路    炼铁5    老炼钢   铁水   主料  300.00  0.821918

In [35]:
ysl_new['重车起点']=ysl_new['来源单元'].map(cell_node)
ysl_new['重车终点']=ysl_new['到达单元'].map(cell_node)
ysl_new['空车起点']=ysl_new['到达单元'].map(cell_node)
ysl_new['空车终点']=ysl_new['来源单元'].map(cell_node)

f:\陶士来文件\software\python3_6_5\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
f:\陶士来文件\software\python3_6_5\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
f:\陶士来文件\software\python3_6_5\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation:

In [36]:
ysl_new=ysl_new.sort_values(by='日运输量',ascending=False)

In [37]:
ysl_new['日运输量'].describe()

count    95.000000
mean      0.135048
std       0.268045
min       0.000055
25%       0.006479
50%       0.043781
75%       0.106616
max       1.518219
Name: 日运输量, dtype: float64

In [38]:
ysl_new.to_excel('龙钢运输量表.xlsx',index=False)

In [39]:
ysl_new.to_csv('龙钢运输量表.csv',index=False)

In [40]:
df_lg=pd.read_csv('龙钢运输量表.csv')

In [41]:
df_lg=df_lg[df_lg['运输方式']=='公路']
df_lg.head(10)

流转类型 运输方式        来源单元   到达单元 物质名称 物质品类     物质量      日运输量  重车起点  重车终点  空车起点  \
1    铁前   公路       450烧结  炼铁1-4  烧结矿   主料  482.95  1.323151     8     9     9   
3    铁钢   公路       炼铁1-4    新炼钢   铁水   主料  320.00  0.876712     9    32    32   
4    铁钢   公路         炼铁5    老炼钢   铁水   主料  300.00  0.821918    48    43    43   
5    铁前   公路       450烧结    炼铁5  烧结矿   主料  209.75  0.574658     8    48    48   
6    铁前   公路  265+400烧结厂    炼铁5  烧结矿   主料  209.75  0.574658    26    48    48   
9    钢扎   公路         老炼钢     二棒   钢坯   粗钢  140.56  0.385096    43    40    40   
10   铁前   公路       炼焦厂_1  炼铁1-4   焦炭  主产品  139.79  0.382986    31     9     9   
11   铁前   公路       炼焦厂_1    炼铁5   焦炭  主产品  121.42  0.332658    31    48    48   
12   钢扎   公路         新炼钢     高线   钢坯   粗钢  119.54  0.327507    32    42    42   
13   铁前   公路         原料场    石灰厂  石灰石   熔剂  117.86  0.322904     3    15    15   

    空车终点  
1      8  
3      9  
4     48  
5      8  
6     26  
9     43  
10    31  
11    31  
12    32  
13     3

In [42]:
df_lg['物质名称'].unique()

array(['烧结矿', '铁水', '钢坯', '焦炭', '石灰石', '球团矿', '烧结返矿', '废钢', '生石灰', '白云石',
       '高炉除尘灰', '返焦', '块矿返矿', '萤石', '锰矿', '硅石', '炼钢集尘粉', '高炉集尘粉', '轻烧白云石',
       '返球团', 'OG泥', '铁矿石', '钢水罐铸余及事故钢水', '压块OG泥', '连铸切头切尾', '钢包改质剂',
       '合成渣', '废连铸坯及试样', '连铸废旧备件', '轧钢皮', '高炉炉尘', '转炉渣'], dtype=object)

In [43]:
df_lg['物质品类'].unique()

array(['主料', '粗钢', '主产品', '熔剂', '自产物质', '其他副产品', '废钢类', '冶金辅料', '副产品'],
      dtype=object)

In [44]:
df_lg=df_lg[~df_lg['物质品类'].isin(['主料','原料','燃料'])]


In [45]:
df_lg['日运输量']=df_lg['日运输量']*365/350

In [46]:
df_lg.head(10)

流转类型 运输方式   来源单元   到达单元 物质名称  物质品类     物质量      日运输量  重车起点  重车终点  空车起点  \
9    钢扎   公路    老炼钢     二棒   钢坯    粗钢  140.56  0.401600    43    40    40   
10   铁前   公路  炼焦厂_1  炼铁1-4   焦炭   主产品  139.79  0.399400    31     9     9   
11   铁前   公路  炼焦厂_1    炼铁5   焦炭   主产品  121.42  0.346914    31    48    48   
12   钢扎   公路    新炼钢     高线   钢坯    粗钢  119.54  0.341543    32    42    42   
13   铁前   公路    原料场    石灰厂  石灰石    熔剂  117.86  0.336743     3    15    15   
17   钢扎   公路    新炼钢     窄带   钢坯    粗钢   65.47  0.187057    32    58    58   
18   钢扎   公路    老炼钢     三棒   钢坯    粗钢   58.80  0.168000    43    45    45   
23   回收   公路   废钢堆场    新炼钢   废钢  自产物质   43.20  0.123429    46    32    32   
25   铁前   公路    石灰厂  450烧结  生石灰   主产品   31.85  0.091000    15     8     8   
28   回收   公路   废钢堆场    老炼钢   废钢  自产物质   29.44  0.084114    46    43    43   

    空车终点  
9     43  
10    31  
11    31  
12    32  
13     3  
17    32  
18    43  
23    46  
25    15  
28    46

In [47]:
df_lg.describe()

物质量       日运输量       重车起点       重车终点       空车起点       空车终点
count   72.000000  72.000000  72.000000  72.000000  72.000000  72.000000
mean    19.078750   0.054511  21.277778  26.694444  26.694444  21.277778
std     32.631981   0.093234  18.064222  17.818837  17.818837  18.064222
min      0.020000   0.000057   3.000000   3.000000   3.000000   3.000000
25%      1.477500   0.004221   3.000000   8.000000   8.000000   3.000000
50%      5.970000   0.017057  15.000000  32.000000  32.000000  15.000000
75%     18.390000   0.052543  43.000000  43.000000  43.000000  43.000000
max    140.560000   0.401600  48.000000  58.000000  58.000000  48.000000

In [48]:
df_lg.shape

(72, 12)

In [49]:
# np.random.seed(10)
# np.random.randint(8,50,82)

In [57]:
ysl_new.shape

(64, 15)

In [35]:
np.random.randint(10,50,72)

array([47, 47, 22, 33, 12, 27, 13, 17, 11, 45, 28, 28, 48, 22, 26, 16, 37,
       10, 21, 25, 33, 46, 23, 43, 38, 37, 24, 21, 41, 47, 21, 49, 19, 43,
       49, 46, 32, 35, 15, 36, 36, 24, 37, 29, 40, 39, 44, 25, 38, 22, 26,
       49, 43, 19, 21, 38, 14, 44, 38, 20, 25, 27, 19, 17, 48, 26, 29, 41,
       33, 21, 39, 39])

In [58]:
np.random.seed(30)
# df_lg['运输车辆的最大装载量']=np.random.randint(10,50,72)
ysl_new['运输车辆的最大装载量']=np.random.randint(10,50,64)

In [51]:
np.random.seed(50)
df_lg['车次']=np.random.randint(1,100,72)

In [52]:
df_lg['日运输量新']=df_lg['日运输量']/df_lg['车次']*10000

In [53]:
df_temp=df_lg['日运输量新']/df_lg['运输车辆的最大装载量']

In [54]:
df_temp.describe()

count    72.000000
mean      1.179460
std       2.656022
min       0.000354
25%       0.029417
50%       0.174780
75%       0.888722
max      13.856085
dtype: float64

In [55]:
df_lg.describe()

物质量       日运输量       重车起点       重车终点       空车起点       空车终点  \
count   72.000000  72.000000  72.000000  72.000000  72.000000  72.000000   
mean    19.078750   0.054511  21.277778  26.694444  26.694444  21.277778   
std     32.631981   0.093234  18.064222  17.818837  17.818837  18.064222   
min      0.020000   0.000057   3.000000   3.000000   3.000000   3.000000   
25%      1.477500   0.004221   3.000000   8.000000   8.000000   3.000000   
50%      5.970000   0.017057  15.000000  32.000000  32.000000  15.000000   
75%     18.390000   0.052543  43.000000  43.000000  43.000000  43.000000   
max    140.560000   0.401600  48.000000  58.000000  58.000000  48.000000   

       运输车辆的最大装载量         车次       日运输量新  
count   72.000000  72.000000   72.000000  
mean    31.152778  47.472222   31.152054  
std     11.243351  31.283336   68.317357  
min     10.000000   1.000000    0.013825  
25%     21.750000  20.750000    1.002728  
50%     30.500000  46.500000    6.403025  
75%     40.250000  72.000000   19.791667  
max     49.000000  97.000000  374.114286

In [56]:
df_lg['车辆折算系数']=df_lg['运输车辆的最大装载量']/(59/2)*(5.1/2)


In [59]:
ysl_new['车辆折算系数']=ysl_new['运输车辆的最大装载量']/(59/2)*(5.1/2)

In [60]:
ysl_new.head()

流转类型 运输方式 来源单元    到达单元        物质名称    物质量      日运输量  重车起点  重车终点  空车起点  \
0  回收物流   道路  炼钢1  废钢堆场_1  钢水罐铸余及事故钢水   9.37  0.026771  28.0  15.0  15.0   
1  回收物流   道路  炼钢1  废钢堆场_1      连铸切头切尾   4.68  0.013371  28.0  15.0  15.0   
2  回收物流   道路  炼钢1  废钢堆场_1     废连铸坯及试样   2.60  0.007429  28.0  15.0  15.0   
3  回收物流   道路  炼钢1  废钢堆场_1      连铸废旧备件   1.33  0.003800  28.0  15.0  15.0   
4  回收物流   道路  炼钢1    原料厂1       炼钢集尘粉  20.82  0.059486  28.0  17.0  17.0   

   空车终点  运输车辆的最大装载量  车次  日运输量新    车辆折算系数  
0  28.0          47 NaN    NaN  4.062712  
1  28.0          47 NaN    NaN  4.062712  
2  28.0          22 NaN    NaN  1.901695  
3  28.0          33 NaN    NaN  2.852542  
4  28.0          12 NaN    NaN  1.037288

In [63]:
ysl_new['重车起点']=ysl_new['重车起点']+1
ysl_new['重车终点']=ysl_new['重车终点']+1
ysl_new['空车起点']=ysl_new['空车起点']+1
ysl_new['空车终点']=ysl_new['空车终点']+1

In [64]:
ysl_new.head()

流转类型 运输方式 来源单元    到达单元        物质名称    物质量      日运输量  重车起点  重车终点  空车起点  \
0  回收物流   道路  炼钢1  废钢堆场_1  钢水罐铸余及事故钢水   9.37  0.026771  29.0  16.0  16.0   
1  回收物流   道路  炼钢1  废钢堆场_1      连铸切头切尾   4.68  0.013371  29.0  16.0  16.0   
2  回收物流   道路  炼钢1  废钢堆场_1     废连铸坯及试样   2.60  0.007429  29.0  16.0  16.0   
3  回收物流   道路  炼钢1  废钢堆场_1      连铸废旧备件   1.33  0.003800  29.0  16.0  16.0   
4  回收物流   道路  炼钢1    原料厂1       炼钢集尘粉  20.82  0.059486  29.0  18.0  18.0   

   空车终点  运输车辆的最大装载量  车次  日运输量新    车辆折算系数  
0  29.0          47 NaN    NaN  4.062712  
1  29.0          47 NaN    NaN  4.062712  
2  29.0          22 NaN    NaN  1.901695  
3  29.0          33 NaN    NaN  2.852542  
4  29.0          12 NaN    NaN  1.037288

In [66]:
ysl_new.to_excel('日照钢铁物料运输量表_new.xlsx',index=False)

In [57]:
df_lg['车次'].sum()

3418

In [58]:
df_lg.head()

流转类型 运输方式   来源单元   到达单元 物质名称 物质品类     物质量      日运输量  重车起点  重车终点  空车起点  \
9    钢扎   公路    老炼钢     二棒   钢坯   粗钢  140.56  0.401600    43    40    40   
10   铁前   公路  炼焦厂_1  炼铁1-4   焦炭  主产品  139.79  0.399400    31     9     9   
11   铁前   公路  炼焦厂_1    炼铁5   焦炭  主产品  121.42  0.346914    31    48    48   
12   钢扎   公路    新炼钢     高线   钢坯   粗钢  119.54  0.341543    32    42    42   
13   铁前   公路    原料场    石灰厂  石灰石   熔剂  117.86  0.336743     3    15    15   

    空车终点  运输车辆的最大装载量  车次       日运输量新    车辆折算系数  
9     43          47  49   81.959184  4.062712  
10    31          47  97   41.175258  4.062712  
11    31          22  12  289.095238  1.901695  
12    32          33  34  100.453782  2.852542  
13     3          12  95   35.446617  1.037288

In [59]:
df_lg.to_csv('龙钢运输量表_final.csv',index=False)

In [60]:
df_lg.to_excel('龙钢运输量表_final.xlsx',index=False)

In [61]:
# set(ysl_new['物质名称'])

In [45]:
ls

 Volume in drive E is 学校资料资源教学
 Volume Serial Number is 5ADC-AF84

 Directory of E:\tsl_file\python_project\gene

2020/03/26  11:24    <DIR>          .
2020/03/26  11:24    <DIR>          ..
2020/03/26  11:23    <DIR>          .idea
2020/03/25  16:32    <DIR>          .ipynb_checkpoints
2020/03/18  10:58           712,932 1.总览.pdf
2020/03/18  11:24           281,284 2.数据结构.pdf
2020/03/26  10:26            27,221 2018年运输量表-766万吨产能 20190410(1).xlsx
2020/03/18  16:18           915,928 3.快速入门.pdf
2020/03/18  13:32         1,025,649 4.进化算法模板.pdf
2020/03/24  17:03           479,811 5.多染色体混合编码.pdf
2020/03/24  17:08           231,949 6.多种群进化优化.pdf
2020/03/25  14:39            14,231 distance.csv
2020/03/25  15:54            14,119 FD.csv
2020/03/25  15:54            14,119 FF.csv
2020/03/25  15:54            14,119 FHV.csv
2020/03/25  15:54            14,255 FW.csv
2020/03/17  14:55    <DIR>          geatpy_example
2020/03/17  12:32             7,959 gene.py
2020/03/25  14:24             1,271

In [51]:
path='all_2018.xlsx'
df_all=pd.read_excel(path)

In [52]:
df_all.columns

Index([], dtype='object')

In [54]:
a=np.inf

In [55]:
type(a)

float

In [56]:
a>3

True

In [57]:
a>999999999

True

In [58]:
3*a

inf

In [1]:
import numpy as np

In [2]:
x=np.random.randint(0,2,(3,3))
x

array([[0, 1, 0],
       [1, 0, 1],
       [0, 0, 1]])

In [3]:
x

array([[0, 1, 0],
       [1, 0, 1],
       [0, 0, 1]])

In [4]:
np.sum(x,axis=0)

array([1, 1, 2])

In [5]:
np.sum(x,axis=1)

array([1, 2, 1])

In [6]:
data=[[ 0,  0,  0,  0,  0,  0,  0,  0,  1,  0,],
 [ 0,  0,  0,  0,  0,  0,  1,  0,  0,  0,],
 [ 0,  1,  0,  0,  0,  0,  0,  0,  0,  0,],
 [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,],
 [ 0,  0,  1,  0,  0,  0,  0,  0,  0,  0,],
 [ 0,  0,  0,  0,  0,  1,  0,  0,  0,  0,],
 [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,],
 [ 0,  0,  0, -0,  0,  0,  0,  1,  0,  0,],
 [ 0,  0,  0,  0,  1,  0,  0,  0,  0,  0,],
 [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,],]
data=np.array(data)

In [7]:
data

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [8]:
data[data>0]

array([1, 1, 1, 1, 1, 1, 1, 1])

In [9]:
data_pair=np.where(data>0)
data_pair

(array([0, 1, 2, 4, 5, 6, 7, 8], dtype=int64),
 array([8, 6, 1, 2, 5, 9, 7, 4], dtype=int64))

In [10]:
node_sort={}
for each_pair in zip(data_pair[0],data_pair[1]):
    print(each_pair)
    node_sort[each_pair[0]]=each_pair[1]
    

(0, 8)
(1, 6)
(2, 1)
(4, 2)
(5, 5)
(6, 9)
(7, 7)
(8, 4)


In [11]:
node_sort

{0: 8, 1: 6, 2: 1, 4: 2, 5: 5, 6: 9, 7: 7, 8: 4}

In [29]:

def show_sort():
    if i==0:
     return node_sort[0]
    else:
        show_sort()
    
     
for _ in range(len(node_sort)):
    print()
    
                
        
        
show_sort(0)

TypeError: show_sort() takes 0 positional arguments but 1 was given