In [1]:
import pandas as pd
import numpy as np

In [2]:
# one_brake=all_brake_boat[0]['brake_boat']

In [3]:
# one_brake

In [10]:
all_brake_boat={0: {'brake_boat': {38: [(0, 0), (124.97, 15.87)], 8: [(0, 15.87), (124.97, 15.87)], 28: [(124.97, 0), (124.97, 15.87)], 18: [(124.97, 15.87), (124.97, 15.87)]}, 'best_use_rate': 0.8333083613445378}, 1: {'brake_boat': {36: [(0, 0), (104.9, 16.62)], 19: [(0, 16.62), (111.34, 15.81)], 29: [(104.9, 0), (111.34, 15.81)], 39: [(111.34, 16.62), (111.34, 15.81)]}, 'best_use_rate': 0.7378460294117647}, 2: {'brake_boat': {34: [(0, 0), (96.34, 16.2)], 14: [(0, 16.2), (96.34, 16.2)], 6: [(96.34, 0), (104.9, 16.62)], 9: [(96.34, 16.62), (111.34, 15.81)]}, 'best_use_rate': 0.6959180042016807}, 3: {'brake_boat': {4: [(0, 0), (96.34, 16.2)], 25: [(96.34, 0), (126.74, 20.51)], 24: [(0, 16.2), (96.34, 16.2)]}, 'best_use_rate': 0.6009299789915966}, 4: {'brake_boat': {15: [(0, 0), (126.74, 20.51)], 35: [(126.74, 0), (126.74, 20.51)]}, 'best_use_rate': 0.5461002941176472}, 5: {'brake_boat': {5: [(0, 0), (126.74, 20.51)], 7: [(126.74, 0), (127.14, 18.32)]}, 'best_use_rate': 0.5177145168067228}, 6: {'brake_boat': {37: [(0, 0), (127.14, 18.32)], 27: [(127.14, 0), (127.14, 18.32)]}, 'best_use_rate': 0.4893287394957983}, 7: {'brake_boat': {17: [(0, 0), (127.14, 18.32)], 31: [(127.14, 0), (112.88, 19.52)]}, 'best_use_rate': 0.47611579831932777}, 8: {'brake_boat': {21: [(0, 0), (112.88, 19.52)], 1: [(112.88, 0), (112.88, 19.52)]}, 'best_use_rate': 0.4629028571428571}, 9: {'brake_boat': {11: [(0, 0), (112.88, 19.52)], 13: [(112.88, 0), (102.52, 21.0)]}, 'best_use_rate': 0.45759848739495795}, 10: {'brake_boat': {23: [(0, 0), (102.52, 21.0)], 3: [(102.52, 0), (102.52, 21.0)]}, 'best_use_rate': 0.45229411764705885}, 11: {'brake_boat': {33: [(0, 0), (102.52, 21.0)], 22: [(102.52, 0), (107.59, 19.28)]}, 'best_use_rate': 0.44403941176470585}, 12: {'brake_boat': {12: [(0, 0), (107.59, 19.28)], 32: [(107.59, 0), (107.59, 19.28)]}, 'best_use_rate': 0.43578470588235296}, 13: {'brake_boat': {2: [(0, 0), (107.59, 19.28)], 10: [(107.59, 0), (104.77, 17.68)]}, 'best_use_rate': 0.4124652100840336}, 14: {'brake_boat': {20: [(0, 0), (104.77, 17.68)], 30: [(104.77, 0), (104.77, 17.68)]}, 'best_use_rate': 0.38914571428571426}, 15: {'brake_boat': {0: [(0, 0), (104.77, 17.68)], 16: [(104.77, 0), (104.9, 16.62)]}, 'best_use_rate': 0.37770710084033615}, 16: {'brake_boat': {26: [(0, 0), (104.9, 16.62)]}, 'best_use_rate': 0.183134243697479}}
all_brake_boat={0: {'brake_boat': {8: [(0, 0), (110.0, 19.22)], 7: [(110.0, 0), (103.0, 16.0)], 1: [(110.0, 16.0), (85.5, 16.3)]}, 'best_use_rate': 0.5415808823529412}, 1: {'brake_boat': {2: [(0, 0), (110.0, 19.22)], 4: [(110.0, 0), (110.0, 17.0)]}, 'best_use_rate': 0.41850840336134454}, 2: {'brake_boat': {3: [(0, 0), (110.0, 17.0)], 6: [(110.0, 0), (110.0, 17.0)]}, 'best_use_rate': 0.39285714285714285}, 3: {'brake_boat': {0: [(0, 0), (85.5, 16.3)], 5: [(85.5, 0), (107.0, 17.0)]}, 'best_use_rate': 0.33746323529411765}}
all_brake_boat={0: {'brake_boat': {4: [(0, 0), (110.0, 19.22)], 3: [(110.0, 0), (103.0, 16.0)], 0: [(110.0, 16.0), (85.5, 16.3)]}, 'best_use_rate': 0.5415808823529412}, 1: {'brake_boat': {2: [(0, 0), (110.0, 17.0)], 1: [(110.0, 0), (110.0, 17.0)]}, 'best_use_rate': 0.39285714285714285}}

def convert_one_brake_coord(one_brake):
    all_keys=list(one_brake.keys())
    all_values=one_brake.values()
    all_values=list(all_values)
    length=len( all_values)
    brake_coord_L=[each[0][0] for each in list(all_values)]
    brake_coord_W=[each[0][1] for each in list(all_values)]


    brake_coord_L_series=pd.Series(brake_coord_L).rank(method='dense',ascending=True)
    brake_coord_W_series=pd.Series(brake_coord_W).rank(method='dense',ascending=True)

    brake_coord_L_rank=[each-1 for each in brake_coord_L_series]
    brake_coord_W_rank=[each-1 for each in brake_coord_W_series]
    
    
    df=pd.DataFrame(data=np.array([brake_coord_L,brake_coord_W]).T,columns=['L','W'])
    if df['W'].nunique()<=1:
        df2=df['L'].rank(method='dense',ascending=True).reset_index().rename(columns={'index':'level_1'})
    else:
        df2=df.groupby('W').apply(lambda df:df['L'].rank(method='dense',ascending=True)).reset_index()
        df2=df2.drop('W',axis=1)
    
    
    df2=df2.rename(columns={'L':'L_rank_raw'})
    print(df2.columns)
    print('df2',df2)
    brake_coord_L_series_compact=pd.merge(df,df2, left_index=True,right_on='level_1',sort=True)['L_rank_raw']
    brake_coord_L_rank=[each-1 for each in brake_coord_L_series_compact]
    
    
    ##将宽度W对应的1排名，全部改成2
    brake_coord_W_rank_new=[each if each==0 else 2 for each in  brake_coord_W_rank ]
    ##转成整形
    brake_coord_W_rank_new=[str(int(each)) for each in brake_coord_W_rank_new]
    brake_coord_L_rank=[str(int(each)) for each in brake_coord_L_rank ]
    
    
    XW_YL=list(zip(brake_coord_W_rank_new,brake_coord_L_rank))
    
    for ind in  range(length):
        all_values[ind].append(','.join(XW_YL[ind]))
        
    one_brake_new={}
    for i in  range(length):
        one_brake_new[all_keys[i]]=all_values[i]
    return one_brake_new
def convert_all_brakes_coord(all_brake_boat):
    all_brake_boat_new={}
    for k in all_brake_boat:
        one_brake=all_brake_boat[k]['brake_boat']
        print('one_brake',one_brake)
        one_brake_new=convert_one_brake_coord(one_brake)
        all_brake_boat[k]['brake_boat']=one_brake_new
        print('one_brake_new',one_brake_new)
    
    return all_brake_boat

In [11]:
res=convert_all_brakes_coord(all_brake_boat)

one_brake {4: [(0, 0), (110.0, 19.22)], 3: [(110.0, 0), (103.0, 16.0)], 0: [(110.0, 16.0), (85.5, 16.3)]}
Index(['level_1', 'L_rank_raw'], dtype='object')
df2    level_1  L_rank_raw
0        0         1.0
1        1         2.0
2        2         1.0
one_brake_new {4: [(0, 0), (110.0, 19.22), '0,0'], 3: [(110.0, 0), (103.0, 16.0), '0,1'], 0: [(110.0, 16.0), (85.5, 16.3), '2,0']}
one_brake {2: [(0, 0), (110.0, 17.0)], 1: [(110.0, 0), (110.0, 17.0)]}
Index(['level_1', 'L_rank_raw'], dtype='object')
df2    level_1  L_rank_raw
0        0         1.0
1        1         2.0
one_brake_new {2: [(0, 0), (110.0, 17.0), '0,0'], 1: [(110.0, 0), (110.0, 17.0), '0,1']}


In [12]:
res

{0: {'brake_boat': {4: [(0, 0), (110.0, 19.22), '0,0'],
   3: [(110.0, 0), (103.0, 16.0), '0,1'],
   0: [(110.0, 16.0), (85.5, 16.3), '2,0']},
  'best_use_rate': 0.5415808823529412},
 1: {'brake_boat': {2: [(0, 0), (110.0, 17.0), '0,0'],
   1: [(110.0, 0), (110.0, 17.0), '0,1']},
  'best_use_rate': 0.39285714285714285}}

In [8]:
one_brake={
			36: [(0, 0), (104.9, 16.62)],
			19: [(0, 16.62), (111.34, 15.81), (2, 0.0)],
			29: [(104.9, 0), (111.34, 15.81), (0.0, 1.0)],
			39: [(111.34, 16.62), (111.34, 15.81), (2, 2.0)],
		}

In [7]:
# one_brake

In [8]:
convert_one_brake_coord(one_brake)

{36: [(0, 0), (104.9, 16.62), (0.0, 0.0)],
 19: [(0, 16.62), (111.34, 15.81), (2, 0.0), (2, 0.0)],
 29: [(104.9, 0), (111.34, 15.81), (0.0, 1.0), (0.0, 1.0)],
 39: [(111.34, 16.62), (111.34, 15.81), (2, 2.0), (2, 2.0)]}

In [9]:
convert_all_brakes_coord(all_brake_boat)

one_brake {38: [(0, 0), (124.97, 15.87), (0.0, 0.0)], 8: [(0, 15.87), (124.97, 15.87), (2, 0.0)], 28: [(124.97, 0), (124.97, 15.87), (0.0, 1.0)], 18: [(124.97, 15.87), (124.97, 15.87), (2, 1.0)]}
one_brake_new {38: [(0, 0), (124.97, 15.87), (0.0, 0.0), (0.0, 0.0)], 8: [(0, 15.87), (124.97, 15.87), (2, 0.0), (2, 0.0)], 28: [(124.97, 0), (124.97, 15.87), (0.0, 1.0), (0.0, 1.0)], 18: [(124.97, 15.87), (124.97, 15.87), (2, 1.0), (2, 1.0)]}
one_brake {36: [(0, 0), (104.9, 16.62), (0.0, 0.0)], 19: [(0, 16.62), (111.34, 15.81), (2, 0.0)], 29: [(104.9, 0), (111.34, 15.81), (0.0, 1.0)], 39: [(111.34, 16.62), (111.34, 15.81), (2, 2.0)]}
one_brake_new {36: [(0, 0), (104.9, 16.62), (0.0, 0.0), (0.0, 0.0)], 19: [(0, 16.62), (111.34, 15.81), (2, 0.0), (2, 0.0)], 29: [(104.9, 0), (111.34, 15.81), (0.0, 1.0), (0.0, 1.0)], 39: [(111.34, 16.62), (111.34, 15.81), (2, 2.0), (2, 2.0)]}
one_brake {34: [(0, 0), (96.34, 16.2), (0.0, 0.0)], 14: [(0, 16.2), (96.34, 16.2), (2, 0.0)], 6: [(96.34, 0), (104.9, 16.6

{0: {'brake_boat': {38: [(0, 0), (124.97, 15.87), (0.0, 0.0), (0.0, 0.0)],
   8: [(0, 15.87), (124.97, 15.87), (2, 0.0), (2, 0.0)],
   28: [(124.97, 0), (124.97, 15.87), (0.0, 1.0), (0.0, 1.0)],
   18: [(124.97, 15.87), (124.97, 15.87), (2, 1.0), (2, 1.0)]},
  'best_use_rate': 0.8333083613445378},
 1: {'brake_boat': {36: [(0, 0), (104.9, 16.62), (0.0, 0.0), (0.0, 0.0)],
   19: [(0, 16.62), (111.34, 15.81), (2, 0.0), (2, 0.0)],
   29: [(104.9, 0), (111.34, 15.81), (0.0, 1.0), (0.0, 1.0)],
   39: [(111.34, 16.62), (111.34, 15.81), (2, 2.0), (2, 2.0)]},
  'best_use_rate': 0.7378460294117647},
 2: {'brake_boat': {34: [(0, 0), (96.34, 16.2), (0.0, 0.0), (0.0, 0.0)],
   14: [(0, 16.2), (96.34, 16.2), (2, 0.0), (2, 0.0)],
   6: [(96.34, 0), (104.9, 16.62), (0.0, 1.0), (0.0, 1.0)],
   9: [(96.34, 16.62), (111.34, 15.81), (2, 1.0), (2, 1.0)]},
  'best_use_rate': 0.6959180042016807},
 3: {'brake_boat': {4: [(0, 0), (96.34, 16.2), (0.0, 0.0), (0.0, 0.0)],
   25: [(96.34, 0), (126.74, 20.51), (0.0

In [10]:
all_values=one_brake.values()

In [11]:
all_values

dict_values([[(0, 0), (104.9, 16.62), (0.0, 0.0)], [(0, 16.62), (111.34, 15.81), (2, 0.0), (2, 0.0)], [(104.9, 0), (111.34, 15.81), (0.0, 1.0), (0.0, 1.0)], [(111.34, 16.62), (111.34, 15.81), (2, 2.0), (2, 2.0)]])

In [12]:
sorted(one_brake.items(),key=lambda x:(x[1][0],x[1][1]))

[(36, [(0, 0), (104.9, 16.62), (0.0, 0.0)]),
 (19, [(0, 16.62), (111.34, 15.81), (2, 0.0), (2, 0.0)]),
 (29, [(104.9, 0), (111.34, 15.81), (0.0, 1.0), (0.0, 1.0)]),
 (39, [(111.34, 16.62), (111.34, 15.81), (2, 2.0), (2, 2.0)])]

In [ ]:
15: {
		'brake_boat': {
			0: [(0, 0), (104.77, 17.68)],
			16: [(104.77, 0), (104.9, 16.62)]
		},

In [13]:
one_brake={
			36: [(0, 0), (104.9, 16.62)],
			19: [(0, 16.62), (111.34, 15.81), (2, 0.0)],
			29: [(104.9, 0), (111.34, 15.81), (0.0, 1.0)],
			39: [(111.34, 16.62), (111.34, 15.81), (2, 2.0)],
		}

In [32]:
# coords=[(0,0),(100,0),(100,18),(190,18)]
# coords=[(0,0),(0,16.62),(104.9,0),(111.34,16.62)]
coords=[(0,0),(104.77,0)]

In [33]:
all_values=[[each] for each in coords]

In [34]:
brake_coord_L=[each[0][0] for each in list(all_values)]
brake_coord_W=[each[0][1] for each in list(all_values)]

# print(brake_coord_L)
# print(brake_coord_W)




brake_coord_L_series=pd.Series(brake_coord_L).rank(method='dense',ascending=True)
brake_coord_W_series=pd.Series(brake_coord_W).rank(method='dense',ascending=True)







brake_coord_L_rank=[each-1 for each in brake_coord_L_series]
brake_coord_W_rank=[each-1 for each in brake_coord_W_series]






In [35]:
#brake_coord_L_series_compact=df.groupby('W').apply(lambda df:df['L'].rank(method='dense',ascending=True)).reset_index(drop=True)

df=pd.DataFrame(data=np.array([brake_coord_L,brake_coord_W]).T,columns=['L','W'])


In [20]:
df

L    W
0    0.00  0.0
1  104.77  0.0

In [29]:
df

L      W
0    0.00   0.00
1    0.00  16.62
2  104.90   0.00
3  111.34  16.62

In [41]:
df['W'].nunique()

1

In [36]:
df2=df.groupby('W').apply(lambda df:df['L'].rank(method='dense',ascending=True))#.reset_index()


In [44]:
df['L'].rank(method='dense',ascending=True).reset_index().rename(columns={'index':'level_1'})

level_1    L
0        0  1.0
1        1  2.0

In [39]:
df2

L      0    1
W            
0.0  1.0  2.0

In [38]:
df2.reset_index()

L    W    0    1
0  0.0  1.0  2.0

In [31]:
df2.reset_index()

W  level_1    L
0   0.00        0  1.0
1   0.00        2  2.0
2  16.62        1  1.0
3  16.62        3  2.0

In [ ]:
# df2=df2.drop('W',axis=1)
# df2=df2.rename(columns={'L':'L_rank_raw'})

In [ ]:

brake_coord_L_series_compact=pd.merge(df,df2, left_index=True,right_on='level_1',sort=True)['L_rank_raw']
brake_coord_L_rank_compact=[each-1 for each in brake_coord_L_series_compact]

In [88]:
brake_coord_L

[0, 0, 104.9, 111.34]

In [89]:
brake_coord_W

[0, 16.62, 0, 16.62]

In [90]:
brake_coord_L_rank

[0.0, 0.0, 1.0, 2.0]

In [91]:
brake_coord_L_rank_compact

[0.0, 0.0, 1.0, 1.0]

In [92]:
brake_coord_W_rank

[0.0, 1.0, 0.0, 1.0]

In [67]:
pd.merge(df,df2, left_index=True,right_on='level_1',sort=True)

L      W  W_rank  level_1  L_rank
0    0.00   0.00     0.0        0     1.0
2    0.00  16.62     1.0        1     1.0
1  104.90   0.00     0.0        2     2.0
3  111.34  16.62     1.0        3     2.0

In [117]:
# def get_second(x):
#     return x[x.成绩.rank(method='dense', ascending=False) == 2.0]

# df.groupby('班级').apply(get_second).reset_index(drop=True)


In [74]:
df=pd.DataFrame(data=np.array([brake_coord_L,brake_coord_W]).T,columns=['L','W'])

In [75]:
df

L      W
0    0.00   0.00
1    0.00  16.62
2  104.90   0.00
3  111.34  16.62

In [76]:
def rank_L(df):
    df['L'].rank(method='dense',ascending=True)

In [77]:
df2=df.groupby('W').apply(lambda df:df['L'].rank(method='dense',ascending=True)).reset_index()

In [78]:
df2

W  level_1    L
0   0.00        0  1.0
1   0.00        2  2.0
2  16.62        1  1.0
3  16.62        3  2.0

In [79]:
df2.index

RangeIndex(start=0, stop=4, step=1)

In [80]:
df2=df2.sort_values(by=['W','L'])

In [81]:
df2=df2.drop('W',axis=1)

In [82]:
df2=df2.rename(columns={'L':'L_rank'})

In [83]:
df2

level_1  L_rank
0        0     1.0
1        2     2.0
2        1     1.0
3        3     2.0

In [84]:
pd.merge(df,df2, left_index=True,right_on='level_1',sort=True)

L      W  level_1  L_rank
0    0.00   0.00        0     1.0
2    0.00  16.62        1     1.0
1  104.90   0.00        2     2.0
3  111.34  16.62        3     2.0

In [85]:
brake_coord_W

[0, 16.62, 0, 16.62]

In [86]:
for index, e_w in enumerate(brake_coord_W):
    
    

for index,each in df2.iterrows():
#     print(index,each['W'])

IndentationError: expected an indented block (<ipython-input-86-ce5aa05691bb>, line 5)

In [36]:
df2[df2['W']==0]['L']

0    1.0
1    2.0
Name: L, dtype: float64

In [142]:
pd.merge(df,df2, left_index=True,left_on='level_1')

L_x      W  W_rank  L_y
0    0.00   0.00     0.0  1.0
1    0.00   0.00     0.0  2.0
2  104.90   0.00     0.0  1.0
3  104.90   0.00     0.0  2.0
4    0.00  16.62     1.0  1.0
5    0.00  16.62     1.0  2.0
6  111.34  16.62     1.0  1.0
7  111.34  16.62     1.0  2.0

In [ ]:
dis3 = data3.groupby('distance_group')['case0'].count().reset_index()
list_dis = ['gps incomplete', 'no move', 'in 5 meters', 'in 50 meters','in 500 meters','in 5 km','in 50 km','out 50 km']

dis3['distance_group'] = dis3['distance_group'].astype('category')
dis3['distance_group'].cat.reorder_categories(list_dis, inplace=True)
dis3.sort_values('distance_group',inplace = True)


In [37]:
list_dis=df['W']
list_dis

0     0.00
1    16.62
2     0.00
3    16.62
Name: W, dtype: float64

In [38]:
df2['W']=df2['W'].astype('category')
df2['W'].cat.reorder_categories(list_dis, inplace=True)
df2.sort_values('W',inplace = True)

ValueError: Categorical categories must be unique

In [109]:
##将宽度W对应的1排名，全部改成2
brake_coord_W_rank_new=[each if each==0 else 2 for each in  brake_coord_W_rank ]

In [110]:
brake_coord_W_rank_new

[0.0, 0.0, 2, 2]

In [115]:
# print([i if i == 0 else 100 for i in range(10)])

In [116]:
# XL_YW=list(zip(brake_coord_L_rank,brake_coord_W_rank))
XW_YL=list(zip(brake_coord_W_rank_new,brake_coord_L_rank))
###还要处理，对应相同的W,看一下L是否存在更小的值




In [117]:
XW_YL

[(0.0, 0.0), (0.0, 1.0), (2, 1.0), (2, 2.0)]

In [118]:
brake_coord_W

[0, 0, 18, 18]

In [ ]:
##从小到大排名，返回对应名次

    

In [50]:
brake_coord_W

array([ 0.  , 15.87,  0.  , 15.87])

In [46]:
np.unique(brake_coord_L).argsort()

array([0, 1], dtype=int64)

In [41]:
brake_coord_W.argsort()

array([0, 2, 1, 3], dtype=int64)

In [21]:
import numpy as np

In [48]:
# help(np.argsort)

array([3, 2, 0, 1], dtype=int64)

In [44]:
dd=np.array([3,1,4,2,1])
ind=dd.argsort()
ind

array([1, 4, 3, 0, 2], dtype=int64)

In [45]:
for each in ind:
    print(each,dd[each])

1 1
4 1
3 2
0 3
2 4


In [12]:
def dictionairy():  
 
    # 声明字典
    key_value ={}     
 
    # 初始化
    key_value[2] = 18     
    key_value[1] = 2 
    key_value[5] = 12 
    key_value[4] = 12
    key_value[6] = 18      
    key_value[3] = 323 
 
 
    print ("按值(value)排序:")   
    print(sorted(key_value.items(), key = lambda kv:(kv[1], kv[0])))     
   
def main(): 
    dictionairy()             
      
       
main()

按值(value)排序:
[(1, 2), (4, 12), (5, 12), (2, 18), (6, 18), (3, 323)]


In [13]:
# 声明字典
key_value ={}     

# 初始化
key_value[2] = 56       
key_value[1] = 2 
key_value[5] = 12 
key_value[4] = 24
key_value[6] = 18      
key_value[3] = 323 
key_value.items()

dict_items([(2, 56), (1, 2), (5, 12), (4, 24), (6, 18), (3, 323)])